name: "Test pushed commit with Bats"

on:
  push:
    branches: [main]
    paths:
      - "**/*.sh"
      - "**/*.bah"
      - "**/*.bats"

defaults:
  run:
    shell: bash

env:
  SECRET_DYNV6_TOKEN: ${{ secrets.SECRET_DYNV6_TOKEN }}
  SECRET_DYNV6_ZONEID: ${{ secrets.SECRET_DYNV6_ZONEID }}
  SECRET_DYNV6_TEST_DOMAIN: ${{ secrets.SECRET_DYNV6_TEST_DOMAIN }}
  
jobs:
  unit-integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Github Checkout with submodules
        uses: actions/checkout@v2
        with:
           submodules: true
      
      - name: Install packages and test dig
        run: |- 
          sudo apt-get install jq dnsutils -y &&
          dig _acme-challenge.$SECRET_DYNV6_TEST_DOMAIN TXT
      
      - name: Run Unit and Integration tests with Bats
        run: |-
          ./test/hook.bats -t

  e2e-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Github Checkout with submodules
        uses: actions/checkout@v2
        with:
           submodules: true

      - name: Install packages 
        run: |- 
          sudo apt-get install jq dnsutils
      
      - name: Run End-to-end with Bats and dehydrated
        run: |-
          ./test/e2e.bats -t